import assert from 'node:assert/strict'
import test from 'node:test'
import {
  HISTORY_KIND_ALLIANCE,
  HISTORY_KIND_FACTION_ABSORPTION,
  HISTORY_KIND_FACTION_EMERGED,
  HISTORY_KIND_FACTION_EXTINCT,
  HISTORY_KIND_INCREMENT3_LATCHED,
  HISTORY_KIND_MAJOR_WAR_END,
  HISTORY_KIND_MAJOR_WAR_START,
  HISTORY_KIND_REBELLION_END,
  HISTORY_KIND_REBELLION_START,
  HISTORY_KIND_TRADE_BACKED_REBEL_EXIT,
  HISTORY_KIND_TRADE_PARTNER_JOIN,
  HISTORY_KIND_TRADE_PARTNER_PEEL,
  HISTORY_KIND_TREATY_PEACE,
  HISTORY_KIND_VASSAL_DEFECTION,
  POLITICS_HISTORY_KINDS,
} from './historyKinds.js'

test('politics history kinds include latch membership and absorption events', () => {
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_INCREMENT3_LATCHED))
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_FACTION_EMERGED))
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_FACTION_EXTINCT))
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_FACTION_ABSORPTION))
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_VASSAL_DEFECTION))
})

test('politics history kinds include major war rebellion and treaty kinds', () => {
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_MAJOR_WAR_START))
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_MAJOR_WAR_END))
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_REBELLION_START))
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_REBELLION_END))
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_TREATY_PEACE))
})

test('politics history kinds include soft-power commercial kinds', () => {
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_TRADE_PARTNER_JOIN))
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_TRADE_PARTNER_PEEL))
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_TRADE_BACKED_REBEL_EXIT))
})

test('politics history kinds include alliance from political pressure', () => {
  assert.ok(POLITICS_HISTORY_KINDS.has(HISTORY_KIND_ALLIANCE))
})
